---
parent: 'common/test_cases/origin_release_install_descheduler_gce_39.yml'
overrides:
  sync:
    - "openshift,openshift-ansible=release-3.9"
    - "openshift,image-registry=release-3.9"
    - "openshift,kubernetes-metrics-server=release-3.9"
    - "openshift,origin-web-console-server=release-3.9"
    - "openshift,aos-cd-jobs=master"
    - "openshift,release=master"
    - "openshift,origin=release-3.9"
